#! /bin/sh

set -xue
export DATAtest="${DATA:-${SCRUB_DIR}}"
export COMOUTtest="${COMOUT:-${COM_DIR}}"
export LOG_DIR="${LOG_DIR}"

mkdir -p "$DATAtest" "$COMOUTtest" "$LOG_DIR"
#cp -fp "$CONFIG_YAML_TEMPLATE" "$CONFIG_YAML"
